// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from async.djinni

#import <Foundation/Foundation.h>


/**
 * A wrapper that represents a block or runnable action.
 * \sa \classlink{EventLoop}
 */
@protocol IXNAction

/** Performs the action. */
- (void)run;

@end
