// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_file.djinni

#import "Muse/api/IXNAnnotationFormat.h"
#import <Foundation/Foundation.h>

/**
 * A data structure that corresponds to an Annotation message in the .muse file format.
 * For more information on the file format see: http://developer.choosemuse.com/file-formats/muse
 */
@interface IXNAnnotationData : NSObject
- (nonnull instancetype)initWithData:(nonnull NSString *)data
                              format:(IXNAnnotationFormat)format
                           eventType:(nonnull NSString *)eventType
                             eventId:(nonnull NSString *)eventId
                            parentId:(nonnull NSString *)parentId;
+ (nonnull instancetype)annotationDataWithData:(nonnull NSString *)data
                                        format:(IXNAnnotationFormat)format
                                     eventType:(nonnull NSString *)eventType
                                       eventId:(nonnull NSString *)eventId
                                      parentId:(nonnull NSString *)parentId;

/**
 * This is additional data for the event, can be in any format specified by
 * \classlink{AnnotationFormat}
 */
@property (nonatomic, readonly, nonnull) NSString * data;

/** This specifies the string format of the event data. */
@property (nonatomic, readonly) IXNAnnotationFormat format;

/**
 * This can be used to classify events, for example "blink" or "error".
 * If you do not need this value, set it to the empty string "".
 */
@property (nonatomic, readonly, nonnull) NSString * eventType;

/**
 * This can be used to pair events together or give them unique IDs.
 * If you do not need this value, set it to the empty string "".
 */
@property (nonatomic, readonly, nonnull) NSString * eventId;

/**
 * This can be used to pair events together or give them unique IDs.
 * If you do not need this value, set it to the empty string "".
 */
@property (nonatomic, readonly, nonnull) NSString * parentId;

@end
