// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a DRL_REF packet.
 * \sa \enumlink{MuseDataPacketType,DRL_REF,IXNMuseDataPacketTypeDrlRef}
 * \sa \functionlink{MuseDataPacket,getDrlRefValue,get_drl_ref_value}
 */
typedef NS_ENUM(NSInteger, IXNDrlRef)
{
    /** DRL sensor */
    IXNDrlRefDrl,
    /** REF sensor */
    IXNDrlRefRef,
};
