// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a EEG packet and in a
 * Quantization packet.
 * Enum values correspond to head locations. Check
 * http://developer.choosemuse.com/hardware-firmware/hardware-specifications
 * for details.
 *
 * Raw EEG values are given in microvolts.  EEG derived values may have different units
 * as defined in \classlink{MuseDataPacketType}.
 *
 * \sa \enumlink{MuseDataPacketType,EEG,IXNMuseDataPacketTypeEeg}
 * \sa \functionlink{MuseDataPacket,getEegChannelValue,get_eeg_channel_value}
 */
typedef NS_ENUM(NSInteger, IXNEeg)
{
    /** Left ear */
    IXNEegEEG1,
    /** Left forehead */
    IXNEegEEG2,
    /** Right forehead */
    IXNEegEEG3,
    /** Right ear */
    IXNEegEEG4,
    /** Left auxiliary. */
    IXNEegAUXLEFT,
    /** Right auxiliary. */
    IXNEegAUXRIGHT,
};
