// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from async.djinni

#import <Foundation/Foundation.h>
@protocol IXNAction;


/** Wrapper around a platform-specific event loop. */
@protocol IXNEventLoop

/**
 * Posts an action to the event loop for processing on the next pass.
 * \param action The action to perform.
 */
- (void)post:(nullable id<IXNAction>)action;

/**
 * Posts an action to the event loop for processing after the specified
 * delay in milliseconds has passed.
 * \param action The action to perform.
 * \caseparam{delayMilliseconds, delay_milliseconds, The time to wait before posting the action to the event loop for processing.}
 */
- (void)postDelayed:(nullable id<IXNAction>)action
  delayMilliseconds:(int64_t)delayMilliseconds;

@end
