// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from validation.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Error classifications.
 *
 * These are designed to provide users with courses of action based on the code
 * that's received: e.g. retry on timeout, try a different way of doing the same
 * thing on unimplemented, show the user an error message on failure.
 */
typedef NS_ENUM(NSInteger, IXNErrorType)
{
    /**
     * A generic failure occurred without any further information. Retrying the
     * operation is unlikely to result in success.
     */
    IXNErrorTypeFailure,
    /** Some timeout was exceeded; the operation might succeed if retried. */
    IXNErrorTypeTimeout,
    /**
     * Some resource (queue space, memory, bandwidth) was exhausted. Retry with
     * backoff.
     */
    IXNErrorTypeOverloaded,
    /** Something was tried that isn't implemented. */
    IXNErrorTypeUnimplemented,
};
