// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logging.djinni

#import "Muse/api/IXNLogPacket.h"
#import <Foundation/Foundation.h>


/**
 * User-supplied log message handler.
 *
 * You can provide an instance of this class in order to integrate LibMuse logs
 * into your application's logging system.
 *
 * \sa \classlink{LogManager}
 */
@protocol IXNLogListener

/**
 * Handler method for log messages. These are sent when interesting events
 * happen. A simple handler may just print each message to stderr or stdout
 * separated by newlines. It's also possible to implement arbitrary log
 * policies within this handler.
 *
 * \warning
 * receiveLog may be entered concurrently from multiple threads; if your
 * listener implementation requires synchronization, it should provide its
 * own.
 *
 * \warning
 * Your listener should not make any LibMuse API calls; otherwise, unbounded
 * recursion may occur, leading to resource exhaustion.
 *
 * \param log The log message.
 */
- (void)receiveLog:(nonnull IXNLogPacket *)log;

@end
