// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logging.djinni

#import "Muse/api/IXNSeverity.h"
#import <Foundation/Foundation.h>

/** A log message. */
@interface IXNLogPacket : NSObject
- (nonnull instancetype)initWithSeverity:(IXNSeverity)severity
                                     raw:(BOOL)raw
                                     tag:(nonnull NSString *)tag
                               timestamp:(double)timestamp
                                 message:(nonnull NSString *)message;
+ (nonnull instancetype)logPacketWithSeverity:(IXNSeverity)severity
                                          raw:(BOOL)raw
                                          tag:(nonnull NSString *)tag
                                    timestamp:(double)timestamp
                                      message:(nonnull NSString *)message;

/**
 * Severity of this message.
 * \return The severity of this message.
 */
@property (nonatomic, readonly) IXNSeverity severity;

/**
 * Denotes raw messages.
 *
 * Raw messages are generally short (one or two character) messages that can
 * be passed straight to the screen without any formatting or added
 * newlines. (We use this to reduce the noise level on some of our verbose
 * log mesages.)
 * \return \c true if this is a raw log message, \c false otherwise.
 */
@property (nonatomic, readonly) BOOL raw;

/**
 * Human-readable, usually all-caps, tag for this message, e.g. "CONNECTOR"
 * or "DEVICE".
 * \return The message tag.
 */
@property (nonatomic, readonly, nonnull) NSString * tag;

/**
 * Timestamp for this log, in seconds.
 * \return The timestamp of this log message.
 */
@property (nonatomic, readonly) double timestamp;

/**
 * Content of this log message. Not newline-terminated; handlers should
 * provide their own line-based formatting.
 * \return The log message content.
 */
@property (nonatomic, readonly, nonnull) NSString * message;

@end
