// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libmuse_version.djinni

#import <Foundation/Foundation.h>
@class IXNApiVersion;


/** The version of the LibMuse library. */
@interface IXNLibmuseVersion : NSObject

/**
 * Returns the LibMuse API version.
 * \return the LibMuse API version.
 */
+ (nullable IXNApiVersion *)instance;

@end
