// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Defines all possible Muse presets. See this link for details:
 * http://developer.choosemuse.com/hardware-firmware/headband-configuration-presets
 * <br>
 *
 * Presets are specific to the model of headband.  For example, setting a preset
 * that is intended for a \muse2014 headband on a \muse2016 headband will not work.
 * Attempting to set an incorrect preset on a headband will result
 * in a warning in the log and the incorrect preset will be ignored.  To avoid this, you should
 * first connect to the headband without setting a preset and check the \classlink{MuseConfiguration}
 * to get the model of the headband and then set the appropriate preset.
 * You can also obtain the current preset of the headband from the
 * \classlink{MuseConfiguration}
 * <br>
 *
 * If you change the preset to while the headband is connected, the headband will disconnect.
 * If the preset is valid for that headband model, then the headband will automatically reconnect.
 * If the preset is invalid for that headband model, then the headband will remain disconnected.
 *
 * \sa \classlink{MuseConfiguration}
 */
typedef NS_ENUM(NSInteger, IXNMusePreset)
{
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, no accelerometer, no battery
     * data, no error data, no DRL/REF data.
     * <br>
     *
     * Availability: \muse2014 only
     */
    IXNMusePresetPreset10,
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, 50 sps accelerometer data,
     * 0.1 sps battery data, no error data, no DRL/REF data
     * <br>
     *
     * Availability: \muse2014 only
     */
    IXNMusePresetPreset12,
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, 50 sps accelerometer data,
     * 0.1 sps battery data, real-time error data, 10 bit @ 10 sps DRL/REF data
     * <br>
     *
     * This is the default for \muse2014.
     * <br>
     *
     * Availability: \muse2014 only
     */
    IXNMusePresetPreset14,
    /**
     * 5 CH, 12 bit @ 256 sps, 52 sps accelerometer/gyro, 0.1 sps battery,
     * 32 sps DRL/REF.
     * <br>
     *
     * Availability: \muse2016 only
     */
    IXNMusePresetPreset20,
    /**
     * 4 CH, 12 bit @ 256 sps, 52 sps accelerometer/gyro, 0.1 sps battery,
     * 32 sps DRL/REF.
     * <br>
     *
     * This is the default for \muse2016.
     * <br>
     *
     * Availability: \muse2016 only
     */
    IXNMusePresetPreset21,
    /**
     * 4 CH, 12 bit @ 256 sps, 0.1 sps battery,
     * 32 sps DRL/REF.
     * <br>
     *
     * Availability: \muse2016 only
     */
    IXNMusePresetPreset22,
    /**
     * 6 CH. Factory usage only.  Commercial headbands do not support this preset.
     * <br>
     *
     * Availability: \muse2016 only
     */
    IXNMusePresetPreset23,
    /**
     * 6 CH, 16 bit @ 500 sps, 50 sps accelerometer, 0.1 sps battery,
     * compression OFF, notch filter OFF, no error data, no DRL/REF data
     * <br>
     *
     * Research preset:<br>
     * Only the following data packets are generated with this preset:
     * \enumlink{MuseDataPacketType,EEG,IXNMuseDataPacketTypeEeg},
     * \enumlink{MuseDataPacketType,ACCELEROMETER,IXNMuseDataPacketTypeAccelerometer},
     * \enumlink{MuseDataPacketType,BATTERY,IXNMuseDataPacketTypeBattery}
     * <br>
     * Artifacts are not generated with this preset.<br>
     *
     * Availability: \muse2014 only
     */
    IXNMusePresetPresetAb,
    /**
     * 4 CH, 16 bit @ 500 sps, 50 sps accelerometer, 0.1 sps battery,
     * compression OFF, notch filter OFF, no error data, no DRL/REF data
     * <br>
     *
     * Research preset:<br>
     * Only the following data packets are generated with this preset:
     * \enumlink{MuseDataPacketType,EEG,IXNMuseDataPacketTypeEeg},
     * \enumlink{MuseDataPacketType,ACCELEROMETER,IXNMuseDataPacketTypeAccelerometer},
     * \enumlink{MuseDataPacketType,BATTERY,IXNMuseDataPacketTypeBattery}
     * <br>
     * Artifacts are not generated with this preset.<br>
     *
     * Availability: \muse2014 only
     */
    IXNMusePresetPresetAd,
};
