// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * The model identifier of the headbands.  The model is laser printed on the
 *  inside of the left pod of the headband as either "MU-01" or "MU-02".
 */
typedef NS_ENUM(NSInteger, IXNMuseModel)
{
    /** First model of Muse, Muse 2014 */
    IXNMuseModelMu01,
    /** Muse 2016 with Bluetooth Low Energy support. */
    IXNMuseModelMu02,
};
