// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import "Muse/api/IXNConnectionState.h"
#import <Foundation/Foundation.h>

/** Packet provides information about the connection state. */
@interface IXNMuseConnectionPacket : NSObject
- (nonnull instancetype)initWithPreviousConnectionState:(IXNConnectionState)previousConnectionState
                                 currentConnectionState:(IXNConnectionState)currentConnectionState;
+ (nonnull instancetype)museConnectionPacketWithPreviousConnectionState:(IXNConnectionState)previousConnectionState
                                                 currentConnectionState:(IXNConnectionState)currentConnectionState;

/**
 * Provides access to the previous connection status.
 * \return The prior connection state.
 */
@property (nonatomic, readonly) IXNConnectionState previousConnectionState;

/**
 * Provides access to the current connection status.
 * \return The current (new) connection state.
 */
@property (nonatomic, readonly) IXNConnectionState currentConnectionState;

@end
