// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Notch Frequencies refer to the possible power line frequencies in a
 * geographic area that may create noise in raw EEG data.
 *
 * \muse2014 headbands are equipped with a hardware filter to remove this noise
 * in certain preset configurations.
 *
 * For \muse2016 headbands or \muse2014 headbands using a research preset there
 * is no hardware filtering.
 *
 * \sa \li \classlink{MusePreset}
 * \li http://en.wikipedia.org/wiki/Utility_frequency
 */
typedef NS_ENUM(NSInteger, IXNNotchFrequency)
{
    /** The notch filter is not available on some hardware versions. */
    IXNNotchFrequencyNotchNone,
    /**
     * 50 Hz frequency is used in most parts of the world:
     * Europe, Russia, Africa
     */
    IXNNotchFrequencyNotch50hz,
    /**
     * 60 Hz frequency is used in North America and Asia.
     * This is the default setting.
     */
    IXNNotchFrequencyNotch60hz,
};
