// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from validation.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the level of a result
 */
typedef NS_ENUM(NSInteger, IXNResultLevel)
{
    /** default */
    IXNResultLevelRNone,
    /** success */
    IXNResultLevelRSuccess,
    /** info */
    IXNResultLevelRInfo,
    /** warn */
    IXNResultLevelRWarn,
    /** error */
    IXNResultLevelRError,
    /** debug */
    IXNResultLevelRDebug,
};
