// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from listeners.djinni

#import <Foundation/Foundation.h>


/**
 * Listens for \classlink{ReaderMuse}
 * events related to the playback of the file.
 */
@protocol IXNReaderPlaybackListener

/** Called when playback of muse file has finished (i.e., reach EOF). */
- (void)receivePlaybackDone;

/** Called when playback was interrupted/error occurred when reading the file. */
- (void)receivePlaybackInterrupted;

@end
