// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logging.djinni

#import <Foundation/Foundation.h>

/** The log message severity. */
typedef NS_ENUM(NSInteger, IXNSeverity)
{
    /**
     * Verbose logs. These provide lots of details that are probably irrelevant
     * except for tracing or debugging problems with the headband or library.
     */
    IXNSeveritySevVerbose,
    /**
     * Informational logs. These messages are sent when significant but expected
     * events happen (e.g. a connection started or was completed successfully.)
     */
    IXNSeveritySevInfo,
    /**
     * Warning logs. These messages indicate that something out of the ordinary
     * but recoverable happened (e.g. a connection attempt failed but will be
     * retried automatically.)
     */
    IXNSeveritySevWarn,
    /**
     * %Error logs. These messages indicate that something has gone wrong -- for
     * instance, a connection terminated unexpectedly or a corrupted packet was
     * received.
     */
    IXNSeveritySevError,
    /**
     * Fatal logs. These are sent when the library is in a completely
     * unrecoverable state from which the only reasonable outcome is termination
     * of the running process. The process will be aborted as soon as the log
     * handler returns.
     */
    IXNSeveritySevFatal,
    /**
     * Debug-only logs. These are only interesting to developers trying to track
     * down problems in the library.
     */
    IXNSeveritySevDebug,
    /** Enum size sentinel; not an actual severity. */
    IXNSeverityTotal,
};
