// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import "Muse/api/IXNConnectionState.h"
#import "Muse/api/IXNMuseDataPacketType.h"
#import <Foundation/Foundation.h>
@class IXNStringify;


/**
 * Converts some LibMuse constants to strings.
 *
 * This is primarily used for LibMuse internal logging purposes. Don't use this
 * to generate UI elements; the results are not guaranteed to be human-friendly,
 * nor localized. You may, however, use this for your own logging or debugging
 * purposes.
 */
@interface IXNStringify : NSObject

/**
 * Returns the singleton instance.
 * \return the singleton instance.
 */
+ (nullable IXNStringify *)instance;

/**
 * String packet type.
 *
 * Only the primitive packet types (eeg, accelerometer, gyro, battery,
 * drl_ref) are human-readable. The rest show up as "type_<n>" where n is
 * the integer corresponding to the constant.
 * \param type The packet type.
 * \return The string representation of the packet type.
 */
- (nonnull NSString *)packetType:(IXNMuseDataPacketType)type;

/**
 * String connection state.
 * \param state The connection state.
 * \return The string representation of the connection state.
 */
- (nonnull NSString *)connectionState:(IXNConnectionState)state;

@end
