// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from muse_file.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * File writer timestamp mode.
 */
typedef NS_ENUM(NSInteger, IXNTimestampMode)
{
    /**
     * Legacy mode.
     *
     * Use the current time for everything except data packets. Use the data
     * packet's timestamp field for those.
     */
    IXNTimestampModeLegacy,
    /** Use the current time for timestamps. */
    IXNTimestampModeCurrent,
    /** Use set_timestamp for timestamps. */
    IXNTimestampModeExplicit,
};
